name: E2E Test with Puppeteer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        directory:
          - websockets
          - sse

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Dependencies
        run: yarn --cwd ${{ matrix.directory }}

      - name: Start WebSocket Server
        run: node ${{ matrix.directory }}/server.js &

      - name: Wait for Server to Start
        run: sleep 2

      - name: Run Puppeteer E2E Test
        run: node ${{ matrix.directory }}/e2e-test.js
